name: Public events
timezone: Europe/Helsinki

events:
  - summary: Linux Shell Scripting 1/4
    #id: linux_shell
    description: |
      Did you know that SLURM batch script is a regular BASH shell script mostly? Did you know that when you login to Triton (our computer cluster) your terminal is a fully enabled shell scripting environment? Do you want to know how to create an alias, a function, how to use loops and traps in a shell, work with variables and arrays? This course is oriented on those who want to start using BASH programming fully and use terminal efficiently.
      We expect that course participants are familiar with the shell basics (experience with BASH, ZSH, etc). We somewhat touch the Part 1 of the Linux Shell tutorial, and continue to Part 2. Though we expect that participant knows how to create a directory and can edit file from the linux shell command line. We will be scripting a lot, there will be lots of demos and real practicing.location: Online, register for connection details
      https://scicomp.aalto.fi/training/scip/shell-scripting/
    begin: 2022-03-21 10:00:00
    duration: { hours: 3 }
  - summary: Linux Shell Scripting 2/4
    #id: linux_shell
    description: |
      Did you know that SLURM batch script is a regular BASH shell script mostly? Did you know that when you login to Triton (our computer cluster) your terminal is a fully enabled shell scripting environment? Do you want to know how to create an alias, a function, how to use loops and traps in a shell, work with variables and arrays? This course is oriented on those who want to start using BASH programming fully and use terminal efficiently.
      We expect that course participants are familiar with the shell basics (experience with BASH, ZSH, etc). We somewhat touch the Part 1 of the Linux Shell tutorial, and continue to Part 2. Though we expect that participant knows how to create a directory and can edit file from the linux shell command line. We will be scripting a lot, there will be lots of demos and real practicing.location: Online, register for connection details
      https://scicomp.aalto.fi/training/scip/shell-scripting/
    begin: 2022-03-25 10:00:00
    duration: { hours: 3 }
  - summary: Linux Shell Scripting 3/4
    #id: linux_shell
    description: |
      Did you know that SLURM batch script is a regular BASH shell script mostly? Did you know that when you login to Triton (our computer cluster) your terminal is a fully enabled shell scripting environment? Do you want to know how to create an alias, a function, how to use loops and traps in a shell, work with variables and arrays? This course is oriented on those who want to start using BASH programming fully and use terminal efficiently.
      We expect that course participants are familiar with the shell basics (experience with BASH, ZSH, etc). We somewhat touch the Part 1 of the Linux Shell tutorial, and continue to Part 2. Though we expect that participant knows how to create a directory and can edit file from the linux shell command line. We will be scripting a lot, there will be lots of demos and real practicing.location: Online, register for connection details
      https://scicomp.aalto.fi/training/scip/shell-scripting/
    begin: 2022-03-28 10:00:00
    duration: { hours: 3 }
  - summary: Linux Shell Scripting 4/4
    #id: linux_shell
    description: |
      Did you know that SLURM batch script is a regular BASH shell script mostly? Did you know that when you login to Triton (our computer cluster) your terminal is a fully enabled shell scripting environment? Do you want to know how to create an alias, a function, how to use loops and traps in a shell, work with variables and arrays? This course is oriented on those who want to start using BASH programming fully and use terminal efficiently.
      We expect that course participants are familiar with the shell basics (experience with BASH, ZSH, etc). We somewhat touch the Part 1 of the Linux Shell tutorial, and continue to Part 2. Though we expect that participant knows how to create a directory and can edit file from the linux shell command line. We will be scripting a lot, there will be lots of demos and real practicing.location: Online, register for connection details
      https://scicomp.aalto.fi/training/scip/shell-scripting/
    begin: 2022-04-01 10:00:00
    duration: { hours: 3 }

  - summary: MPI introduction
    #id: mpi_introduction
    description: |
      In this introduction to MPI programming we are going to cover all the basic functionalities of the API,
      and see how these are applied to real problems. Starting from simple, well-established algorithms, we
      will build up towards more advanced and realistic examples commonly found in computational physics and
      chemistry. Finally, we will explore how the strengths of OpenMP multithreading and MPI can be combined
      with hybrid parallel programming.
      https://scicomp.aalto.fi/training/scip/mpi-introduction/
    location: Online, register for connection details
    begin: 2022-03-08 10:00:00
    duration: { hours: 3 }
  - summary: MPI introduction
    #id: mpi_introduction
    description: |
      In this introduction to MPI programming we are going to cover all the basic functionalities of the API,
      and see how these are applied to real problems. Starting from simple, well-established algorithms, we
      will build up towards more advanced and realistic examples commonly found in computational physics and
      chemistry. Finally, we will explore how the strengths of OpenMP multithreading and MPI can be combined
      with hybrid parallel programming.
      https://scicomp.aalto.fi/training/scip/mpi-introduction/
    location: Online, register for connection details
    begin: 2022-03-11 10:00:00
    duration: { hours: 3 }
  - summary: MPI introduction
    #id: mpi_introduction
    description: |
      In this introduction to MPI programming we are going to cover all the basic functionalities of the API,
      and see how these are applied to real problems. Starting from simple, well-established algorithms, we
      will build up towards more advanced and realistic examples commonly found in computational physics and
      chemistry. Finally, we will explore how the strengths of OpenMP multithreading and MPI can be combined
      with hybrid parallel programming.
      https://scicomp.aalto.fi/training/scip/mpi-introduction/
    location: Online, register for connection details
    begin: 2022-03-15 10:00:00
    duration: { hours: 3 }
  - summary: MPI introduction
    #id: mpi_introduction
    description: |
      In this introduction to MPI programming we are going to cover all the basic functionalities of the API,
      and see how these are applied to real problems. Starting from simple, well-established algorithms, we
      will build up towards more advanced and realistic examples commonly found in computational physics and
      chemistry. Finally, we will explore how the strengths of OpenMP multithreading and MPI can be combined
      with hybrid parallel programming.
      https://scicomp.aalto.fi/training/scip/mpi-introduction/
    location: Online, register for connection details
    begin: 2022-03-18 10:00:00
    duration: { hours: 3 }

