name: Public events
timezone: Europe/Helsinki

events:
  - &kickstart-2022-summer
    summary: Scientific Computing Kickstart (+HPC kickstart)
    description:
    location: https://twitch.tv/coderefinery
    description: |
      https://scicomp.aalto.fi/training/scip/summer-kickstart-2022/

      Day 1:

        This course is a general introduction to computational
        researchers. The point is to serve as a guide to your career:
        a map to the types of resources that are available and skills
        you may need in your career, so that you can be prepared when
        you need more in the future. There will also be topics related
        to using these resources. Aalto University is used in some
        examples, but all parts are designed to be useful no matter
        where you are now.

        This course is especially suitable to new researchers or
        students trying to understand computational/data analysis
        options available to them. It won’t go into anything too deep,
        but will provide you with a good background for your next
        steps: you will know what resources are available and know the
        next steps to use them.

      Day 2-3:

        Scientific Computing Kickstart is a three × half day course
        for researchers to get started with scientific computing (day
        1) and high-performance computing (HPC) clusters (day 2). We
        will take you from being a new user to being competent to run
        your code at a larger scale than you could before. (However,
        we don’t cover application-specific matters beyond some
        Python/R/Matlab basics or focus on the high-performance part:
        but this is an easy next step after this course).

        This course is good for any researcher who thinks they may
        need to scale up to larger resources in the next six months,
        in any field. Even if you don’t use computing clusters, you
        will be better prepared to understand how computing works on
        other systems. If you are a student, this is an investment in
        your skills. By the end of the course you get the hints, ready
        solutions and copy/paste examples on how to find, run and
        monitor your applications, and manage your data. In addition
        to how to optimize your workflow in terms of filesystem
        traffic, memory usage etc.
    duration: {hours: 4}
    begin: 2022-06-07 12:00:00
  - <<: *kickstart-2022-summer
    begin: 2022-06-08 12:00:00
  - <<: *kickstart-2022-summer
    begin: 2022-06-09 12:00:00


  - &swd4sc202204
    summary: Software design for scientific computing
    #id: swd4sc202204
    description: |
      Here you can register for our "Hands-on Data Anonymization 2022" More info at: https://scicomp.aalto.fi/training/scip/data-anonymization-workshop-2022/
    duration: { hours: 2 }
    begin: 2022-04-25 12:00:00
  - <<: *swd4sc202204
    begin: 2022-05-03 10:00:00
    duration: { hours: 4 }
  - <<: *swd4sc202204
    begin: 2022-05-09 10:00:00
    duration: { hours: 5 }



  - &anonymization202204
    summary: Hands-on Data Anonymization
    #id: anonymization202204
    description: |
      Here you can register for our "Hands-on Data Anonymization 2022" More info at: https://scicomp.aalto.fi/training/scip/data-anonymization-workshop-2022/
    duration: { hours: 3 }
    begin: 2022-04-04 12:00:00
  - <<: *anonymization202204
    begin: 2022-04-06 12:00:00



  - &debug202204
    summary: Debugging with Python, Matlab, and C/C++
    #id: debug202204
    description: |
      Introduction to Debugging with Python, Matlab, and C/C++ April 2022. This is an online course available to anyone with an internet connection.
      https://docs.google.com/forms/d/e/1FAIpQLSclIA0HH-YeZZ6lhipjMKpfBFDF88WnsXCyc92OseCtdwLSSw/viewform
    duration: { hours: 3 }
    begin: 2022-04-20 12:00:00
  - <<: *debug202204
    begin: 2022-04-21 12:00:00
  - <<: *debug202204
    begin: 2022-04-22 12:00:00



  - &coderifenery202203
    summary: Code Refinery Workshop
    #id: coderifenery202203
    description: |
      https://coderefinery.org/workshops/upcoming/
    duration: { hours: 3.5 }
    begin: 2022-03-22 10:00:00
  - <<: *coderifenery202203
    begin: 2022-03-23 10:00:00
  - <<: *coderifenery202203
    begin: 2022-03-24 10:00:00
  - <<: *coderifenery202203
    begin: 2022-03-29 10:00:00
  - <<: *coderifenery202203
    begin: 2022-03-30 10:00:00
  - <<: *coderifenery202203
    begin: 2022-03-31 10:00:00



  - &linuxshell202203
    summary: Linux Shell Scripting
    #id: linux_shell
    description: |
      Did you know that SLURM batch script is a regular BASH shell script mostly? Did you know that when you login to Triton (our computer cluster) your terminal is a fully enabled shell scripting environment? Do you want to know how to create an alias, a function, how to use loops and traps in a shell, work with variables and arrays? This course is oriented on those who want to start using BASH programming fully and use terminal efficiently.
      We expect that course participants are familiar with the shell basics (experience with BASH, ZSH, etc). We somewhat touch the Part 1 of the Linux Shell tutorial, and continue to Part 2. Though we expect that participant knows how to create a directory and can edit file from the linux shell command line. We will be scripting a lot, there will be lots of demos and real practicing.location: Online, register for connection details
      https://scicomp.aalto.fi/training/scip/shell-scripting/
    duration: { hours: 3 }
    begin: 2022-03-21 12:00:00
  - <<: *linuxshell202203
    begin: 2022-03-25 12:00:00
  - <<: *linuxshell202203
    begin: 2022-03-28 12:00:00
  - <<: *linuxshell202203
    begin: 2022-04-01 12:00:00



  - &mpi-intro-2022
    summary: MPI introduction
    #id: mpi_introduction
    description: |
      In this introduction to MPI programming we are going to cover all the basic functionalities of the API,
      and see how these are applied to real problems. Starting from simple, well-established algorithms, we
      will build up towards more advanced and realistic examples commonly found in computational physics and
      chemistry. Finally, we will explore how the strengths of OpenMP multithreading and MPI can be combined
      with hybrid parallel programming.
      https://scicomp.aalto.fi/training/scip/mpi-introduction/
    location: Online, register for connection details
    begin: 2022-03-08 10:00:00
    duration: { hours: 3 }
  - <<: *mpi-intro-2022
    begin: 2022-03-11 10:00:00
  - <<: *mpi-intro-2022
    begin: 2022-03-15 10:00:00
  - <<: *mpi-intro-2022
    begin: 2022-03-18 10:00:00
